version: '3'
services:
  dev:
    image: node:10
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/service
    command: npm run start:dev
    ports:
      - 1234:1234
      - 1235:1235
      - 3000:3000
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - '27017:27017'
    volumes:
      - .:/usr/src/service/db
    networks:
      - mongo-compose-network

volumes:
  nodemodules:
    external: true
